:fn-what-is-maven: footnote:[https://maven.apache.org/what-is-maven.html[Maven Documentation - What is Maven?]]

= Learning Maven

== Maven

[quote]
Maven, a Yiddish word meaning accumulator of knowledge, began as an attempt to simplify the build processes in the Jakarta Turbine project.
There were several projects, each with their own Ant build files, that were all slightly different.
JARs were checked into CVS.
We wanted a standard way to build the projects, a clear definition of what the project consisted of, an easy way to publish project information, and a way to share JARs across several projects{fn-what-is-maven}.
``

What Maven can do?

* modularize management
* dependencies management
* build
* package
* deploy

=== Installation

==== Installation for local
==== Using IDEA
==== Using IDEA with Docker

A growth idea

. install idea and not use idea default maven
. install docker and deploy maven in docker
. idea use maven in docker
. you get a very clearly computer

=== Commands

=== Structure

=== POM Introduction

=== Plugins

== Maven Using Guidance

=== How to create a maven project

=== How to manage project's dependencies

=== How to build














